apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-api
  namespace: ai
  labels:
    app: ai-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: api
          image: your-registry/ai-api-example:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
            # 从 Secret 注入敏感变量
            - name: DASHSCOPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: DASHSCOPE_API_KEY
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: INTERNAL_API_KEY
          envFrom:
            - configMapRef:
                name: ai-api-config
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
